### ISSUE TITLE
why i setAttibute(key,null) ,i find this error?

### ISSUE THREAD

**Issue by somesky** [jcoleman/tomcat-redis-session-manager#63]
hi,jcoleman:
why i setAttibute(key,null) ,i find this error:
java.lang.NullPointerException
	at com.radiadesign.catalina.session.RedisSession.setAttribute(RedisSession.java:58)
	at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:154)
	at org.apache.struts2.dispatcher.SessionMap.put(SessionMap.java:183)

**Comment by somesky** [comment]
why not find new value is null,remove this key?

**Comment by jcoleman** [comment]
This stack trace isn't from the current version (which as the class package prefix com.orangefunction rather than com.radiadesign).

Your version is no longer supported.

**Comment by somesky** [comment]
Thank you,i will complie and try the version(which as the class package prefix com.orangefunction rather than com.radiadesign).

Best regards!
